[project]
name = "dataloader-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "colorlog>=6.9.0",
    "neo4j>=5.28.1",
    "rich>=14.0.0",
]
